<?php
/**
 * This file is part of the Decode Framework
 * @license http://opensource.org/licenses/MIT
 */
namespace df\apex\directory\front\application\_nodes;

use df;
use df\core;
use df\apex;
use df\halo;
use df\arch;

class TaskGenerateEntry extends arch\node\Task {

    public function execute() {
        $this->io->writeLine('Generating entry point');

        $phpPath = core\environment\Config::getInstance()->getBinaryPath('php');
        $appPath = df\Launchpad::$applicationPath;
        $environmentId = df\Launchpad::$environmentId;

        if($phpPath == 'php') {
            $phpPath = halo\system\Base::getInstance()->which('php');
        }


        $mainFile = new core\fs\File($appPath.'/entry/'.$environmentId.'.php');

        if(!$mainFile->exists()) {
            $mainFile->putContents(
                '<?php'."\n".
                '/* This file is automatically generated by the DF package builder */'."\n".
                'require_once \''.df\Launchpad::$rootPath.'/Df.php\';'."\n".
                'df\Launchpad::run();'."\n"
            );
        }


        $file = core\fs\File::create(
            $appPath.'/entry/'.$environmentId,

            '#!'.$phpPath."\n".
            '<?php'."\n\n".
            '/* This file is automatically generated by the DF package builder */'."\n".
            'require_once \''.$appPath.'/entry/'.$environmentId.'.php\';'."\n"
        );

        core\fs\File::delete($appPath.'/entry/'.$environmentId.'.development.php');
        core\fs\File::delete($appPath.'/entry/'.$environmentId.'.testing.php');
        core\fs\File::delete($appPath.'/entry/'.$environmentId.'.production.php');
    }
}