<?php
/**
 * This file is part of the Decode Framework
 * @license http://opensource.org/licenses/MIT
 */
namespace df\apex\directory\front\app\_nodes;

use df;
use df\core;
use df\apex;
use df\halo;
use df\arch;

use DecodeLabs\Terminus\Cli;
use DecodeLabs\Atlas;
use DecodeLabs\Systemic;

class TaskGenerateEntry extends arch\node\Task
{
    public function execute()
    {
        Cli::{'yellow'}('Generating entry point: ');

        $phpPath = core\environment\Config::getInstance()->getBinaryPath('php');

        $appPath = df\Launchpad::$app->path;
        $envId = df\Launchpad::$app->envId;

        if ($phpPath == 'php') {
            $phpPath = Systemic::$os->which('php');
        }


        $mainFile = Atlas::$fs->file($appPath.'/entry/'.$envId.'.php');

        if (!$mainFile->exists()) {
            $mainFile->putContents(
                '<?php'."\n".
                'require_once dirname(__DIR__).\'/vendor/autoload.php\';'."\n".
                'df\Launchpad::run();'."\n"
            );
        }


        $file = Atlas::$fs->createFile(
            $appPath.'/entry/'.$envId,

            '#!'.$phpPath."\n".
            '<?php'."\n\n".
            '/* This file is automatically generated by the DF package builder */'."\n".
            'require_once __DIR__.\'/'.$envId.'.php\';'."\n"
        );

        Cli::success('done');
    }
}
