<?php 
/**
 * This file is part of the Decode Framework
 * @license http://opensource.org/licenses/MIT
 */
namespace df\apex\directory\front\application\_actions;

use df;
use df\core;
use df\apex;
use df\halo;
use df\arch;
    
class TaskGenerateBaseEntry extends arch\task\Action {

    public function execute() {
        $this->io->writeLine('Generating base entry point');

        $phpPath = core\Environment::getInstance()->getBinaryPath('php');
        $appPath = df\Launchpad::$applicationPath;
        $environmentId = df\Launchpad::$environmentId;

        if($phpPath == 'php') {
            $phpPath = halo\system\Base::getInstance()->which('php');
        }
        

        $file = core\fs\File::create(
            $appPath.'/entry/'.$environmentId, 

            '#!'.$phpPath."\n".
            '<?php'."\n\n".
            '/* This file is automatically generated by the DF package builder */'."\n".
            'require_once \''.$appPath.'/entry/'.$environmentId.'.development.php\';'."\n"
        );
    }
}