<?php 
/**
 * This file is part of the Decode Framework
 * @license http://opensource.org/licenses/MIT
 */
namespace df\apex\directory\front\application\_actions;

use df;
use df\core;
use df\apex;
use df\halo;
use df\arch;
    
class TaskGenerateBaseEntry extends arch\task\Action {

    public function execute() {
        $this->response->writeLine('Generating base entry point');

        $phpPath = core\Environment::getInstance($this->application)->getPhpBinaryPath();
        $appPath = df\Launchpad::$applicationPath;
        $environmentId = df\Launchpad::$environmentId;
        
        $data = '#!'.$phpPath."\n".
                '<?php'."\n\n".
                '/* This file is automatically generated by the DF package builder */'."\n".
                'require_once \''.$appPath.'/entry/'.$environmentId.'.development.php\';'."\n";

        $entryPath = $appPath.'/entry/'.$environmentId;
        file_put_contents($entryPath, $data);

        try {
            core\io\Util::chmod($entryPath, 0777, true);
        } catch(\Exception $e) {}
    }
}